// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrPkxudVkuMSi1iS4A5t_660KXodbvKsE',
    appId: '1:714432337675:web:5951f143cf692f9b7cb40e',
    messagingSenderId: '714432337675',
    projectId: 'study-planner-app-1daab',
    authDomain: 'study-planner-app-1daab.firebaseapp.com',
    storageBucket: 'study-planner-app-1daab.firebasestorage.app',
    measurementId: 'G-DW6GZ0FEPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1wJkggEtg8gZHFX6dmaZS2L_wv1We1AM',
    appId: '1:714432337675:android:440fca9101e262207cb40e',
    messagingSenderId: '714432337675',
    projectId: 'study-planner-app-1daab',
    storageBucket: 'study-planner-app-1daab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgbVPc-1JuJ2wRVt524Qyx6yaQzZTg53E',
    appId: '1:714432337675:ios:b258dbea1c5ffa097cb40e',
    messagingSenderId: '714432337675',
    projectId: 'study-planner-app-1daab',
    storageBucket: 'study-planner-app-1daab.firebasestorage.app',
    androidClientId: '714432337675-pet5bafqkfi2lpsdhif6phaaruo6hqvu.apps.googleusercontent.com',
    iosClientId: '714432337675-s5kkp5if18llo2e6l0tndfbrkbigh67a.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgbVPc-1JuJ2wRVt524Qyx6yaQzZTg53E',
    appId: '1:714432337675:ios:b258dbea1c5ffa097cb40e',
    messagingSenderId: '714432337675',
    projectId: 'study-planner-app-1daab',
    storageBucket: 'study-planner-app-1daab.firebasestorage.app',
    androidClientId: '714432337675-pet5bafqkfi2lpsdhif6phaaruo6hqvu.apps.googleusercontent.com',
    iosClientId: '714432337675-s5kkp5if18llo2e6l0tndfbrkbigh67a.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrPkxudVkuMSi1iS4A5t_660KXodbvKsE',
    appId: '1:714432337675:web:6727c078ece430dd7cb40e',
    messagingSenderId: '714432337675',
    projectId: 'study-planner-app-1daab',
    authDomain: 'study-planner-app-1daab.firebaseapp.com',
    storageBucket: 'study-planner-app-1daab.firebasestorage.app',
    measurementId: 'G-1CSMVZ8339',
  );
}
